"""link annotations to cubes

Revision ID: 7b92fd31f4e4
Revises: 0280780c8eb4
Create Date: 2026-07-02 15:37:16.857083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b92fd31f4e4'
down_revision: Union[str, Sequence[str], None] = '0280780c8eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roi_annotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataset_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cube_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_roi_annotations_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_foreign_key('fk_roi_annotations_cube_id', 'hsi_cubes', ['cube_id'], ['cube_id'])

    # Backfill the query key for pre-existing rows (their target held the dataset id).
    op.execute("UPDATE roi_annotations SET dataset_id = target WHERE dataset_id IS NULL")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roi_annotations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_roi_annotations_cube_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_roi_annotations_dataset_id'))
        batch_op.drop_column('cube_id')
        batch_op.drop_column('dataset_id')

    # ### end Alembic commands ###
