"""add remaining data-model entities

Revision ID: 0280780c8eb4
Revises: 2c25f20d16a3
Create Date: 2026-07-02 15:19:43.000488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0280780c8eb4'
down_revision: Union[str, Sequence[str], None] = '2c25f20d16a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spectral_libraries',
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('library_name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('file_format', sa.String(), nullable=False),
    sa.Column('data_ref', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('num_spectra', sa.Integer(), nullable=True),
    sa.Column('dc_rights', sa.String(), nullable=True),
    sa.Column('dc_creator', sa.String(), nullable=False),
    sa.Column('dc_subject', sa.String(), nullable=True),
    sa.Column('dc_description', sa.String(), nullable=True),
    sa.Column('dc_publisher', sa.String(), nullable=True),
    sa.Column('dc_contributor', sa.String(), nullable=True),
    sa.Column('dc_source', sa.String(), nullable=True),
    sa.Column('dc_identifier', sa.String(), nullable=True),
    sa.Column('sensor_type', sa.String(), nullable=True),
    sa.Column('instrument', sa.String(), nullable=True),
    sa.Column('wavelengths', sa.JSON(), nullable=False),
    sa.Column('wavelength_units', sa.String(), nullable=False),
    sa.Column('fwhm', sa.JSON(), nullable=True),
    sa.Column('number_of_bands', sa.Integer(), nullable=False),
    sa.Column('interleave', sa.String(), nullable=False),
    sa.Column('data_type', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('spectra_names', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('library_id')
    )
    op.create_table('visualisations',
    sa.Column('view_id', sa.Uuid(), nullable=False),
    sa.Column('view_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('display_settings', sa.JSON(), nullable=True),
    sa.Column('dataset_ref', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('view_id')
    )
    op.create_table('external_inputs',
    sa.Column('input_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('source_tool', sa.String(), nullable=False),
    sa.Column('capture_modality', sa.String(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('data_ref', sa.String(), nullable=False),
    sa.Column('capture_date', sa.DateTime(), nullable=True),
    sa.Column('camera_model', sa.String(), nullable=True),
    sa.Column('instrument_id', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('processing_steps', sa.String(), nullable=True),
    sa.Column('dc_rights', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('input_id')
    )
    op.create_table('spectral_extractions',
    sa.Column('extraction_id', sa.Uuid(), nullable=False),
    sa.Column('mean_spectrum', sa.JSON(), nullable=False),
    sa.Column('std_spectrum', sa.JSON(), nullable=False),
    sa.Column('min_spectrum', sa.JSON(), nullable=True),
    sa.Column('max_spectrum', sa.JSON(), nullable=True),
    sa.Column('pixel_count', sa.Integer(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.Column('wavelength_range', sa.String(), nullable=True),
    sa.Column('roi_id', sa.Uuid(), nullable=True),
    sa.Column('library_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['spectral_libraries.library_id'], ),
    sa.ForeignKeyConstraint(['roi_id'], ['roi_annotations.roi_id'], ),
    sa.PrimaryKeyConstraint('extraction_id'),
    sa.UniqueConstraint('roi_id')
    )
    op.create_table('processing_operations',
    sa.Column('operation_id', sa.Uuid(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('method_name', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('software_version', sa.String(), nullable=False),
    sa.Column('was_associated_with', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('input_extraction_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['input_extraction_id'], ['spectral_extractions.extraction_id'], ),
    sa.PrimaryKeyConstraint('operation_id')
    )
    op.create_table('derived_datasets',
    sa.Column('derived_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('data_ref', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('classes', sa.Integer(), nullable=True),
    sa.Column('class_names', sa.JSON(), nullable=True),
    sa.Column('lookup', sa.JSON(), nullable=True),
    sa.Column('dc_rights', sa.String(), nullable=True),
    sa.Column('was_derived_from', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('operation_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['processing_operations.operation_id'], ),
    sa.PrimaryKeyConstraint('derived_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('derived_datasets')
    op.drop_table('processing_operations')
    op.drop_table('spectral_extractions')
    op.drop_table('external_inputs')
    op.drop_table('visualisations')
    op.drop_table('spectral_libraries')
    # ### end Alembic commands ###
