"""initial schema core data model

Revision ID: 7fa9aeabfd39
Revises: 
Create Date: 2026-07-02 14:28:06.497733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa9aeabfd39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('storage_root', sa.String(), nullable=False),
    sa.Column('dc_title', sa.String(), nullable=False),
    sa.Column('dc_creator', sa.String(), nullable=True),
    sa.Column('dc_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('artefacts',
    sa.Column('artefact_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('dc_title', sa.String(), nullable=False),
    sa.Column('dc_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('artefact_id')
    )
    op.create_table('data_acquisitions',
    sa.Column('acquisition_id', sa.Uuid(), nullable=False),
    sa.Column('artefact_id', sa.Uuid(), nullable=False),
    sa.Column('capture_modality', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('instrument_id', sa.String(), nullable=True),
    sa.Column('instrument_settings', sa.JSON(), nullable=True),
    sa.Column('dark_reference', sa.Boolean(), nullable=False),
    sa.Column('white_reference', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['artefact_id'], ['artefacts.artefact_id'], ),
    sa.PrimaryKeyConstraint('acquisition_id')
    )
    op.create_table('hsi_cubes',
    sa.Column('cube_id', sa.Uuid(), nullable=False),
    sa.Column('acquisition_id', sa.Uuid(), nullable=False),
    sa.Column('data_ref', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('samples', sa.Integer(), nullable=False),
    sa.Column('lines', sa.Integer(), nullable=False),
    sa.Column('number_of_bands', sa.Integer(), nullable=False),
    sa.Column('wavelengths', sa.JSON(), nullable=False),
    sa.Column('wavelength_units', sa.String(), nullable=False),
    sa.Column('fwhm', sa.JSON(), nullable=True),
    sa.Column('interleave', sa.String(), nullable=True),
    sa.Column('data_type', sa.Integer(), nullable=True),
    sa.Column('spectral_range_min', sa.Float(), nullable=True),
    sa.Column('spectral_range_max', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['acquisition_id'], ['data_acquisitions.acquisition_id'], ),
    sa.PrimaryKeyConstraint('cube_id')
    )
    op.create_table('roi_annotations',
    sa.Column('roi_id', sa.Uuid(), nullable=False),
    sa.Column('cube_id', sa.Uuid(), nullable=True),
    sa.Column('selector_type', sa.String(), nullable=False),
    sa.Column('selector_value', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('motivation', sa.String(), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cube_id'], ['hsi_cubes.cube_id'], ),
    sa.PrimaryKeyConstraint('roi_id')
    )
    op.create_table('spectral_extractions',
    sa.Column('extraction_id', sa.Uuid(), nullable=False),
    sa.Column('roi_id', sa.Uuid(), nullable=False),
    sa.Column('mean_spectrum', sa.JSON(), nullable=False),
    sa.Column('std_spectrum', sa.JSON(), nullable=True),
    sa.Column('pixel_count', sa.Integer(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['roi_id'], ['roi_annotations.roi_id'], ),
    sa.PrimaryKeyConstraint('extraction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spectral_extractions')
    op.drop_table('roi_annotations')
    op.drop_table('hsi_cubes')
    op.drop_table('data_acquisitions')
    op.drop_table('artefacts')
    op.drop_table('projects')
    # ### end Alembic commands ###
